// Model configurations for different architectures
// Supports YOLO v8/v11/v12 and Vajra

export const MODEL_FAMILIES = {
  YOLO: 'yolo',
  VAJRA: 'vajra',
};

export const MODEL_CONFIGS = {
  // YOLOv8 Models
  yolov8n: {
    id: 'yolov8n',
    name: 'YOLOv8 Nano',
    family: MODEL_FAMILIES.YOLO,
    version: 'v8',
    size: 'nano',
    params: '3.2M',
    flops: '8.7G',
    mapVal: '37.3',
    speed: '80ms',
    description: 'Fastest YOLOv8, great for real-time applications',
    recommended: true,
    requirements: { gpu: false, minRam: '2GB' },
    inputSize: 640,
    downloadUrl: 'yolov8n.pt',
  },
  yolov8s: {
    id: 'yolov8s',
    name: 'YOLOv8 Small',
    family: MODEL_FAMILIES.YOLO,
    version: 'v8',
    size: 'small',
    params: '11.2M',
    flops: '28.6G',
    mapVal: '44.9',
    speed: '128ms',
    description: 'Recommended for fire detection',
    recommended: true,
    requirements: { gpu: false, minRam: '4GB' },
    inputSize: 640,
    downloadUrl: 'yolov8s.pt',
  },
  yolov8m: {
    id: 'yolov8m',
    name: 'YOLOv8 Medium',
    family: MODEL_FAMILIES.YOLO,
    version: 'v8',
    size: 'medium',
    params: '25.9M',
    flops: '78.9G',
    mapVal: '50.2',
    speed: '234ms',
    description: 'Balanced performance and accuracy',
    recommended: false,
    requirements: { gpu: true, minRam: '8GB' },
    inputSize: 640,
    downloadUrl: 'yolov8m.pt',
  },
  yolov8l: {
    id: 'yolov8l',
    name: 'YOLOv8 Large',
    family: MODEL_FAMILIES.YOLO,
    version: 'v8',
    size: 'large',
    params: '43.7M',
    flops: '165.2G',
    mapVal: '52.9',
    speed: '375ms',
    description: 'High accuracy detection',
    recommended: false,
    requirements: { gpu: true, minRam: '12GB' },
    inputSize: 640,
    downloadUrl: 'yolov8l.pt',
  },
  yolov8x: {
    id: 'yolov8x',
    name: 'YOLOv8 XLarge',
    family: MODEL_FAMILIES.YOLO,
    version: 'v8',
    size: 'xlarge',
    params: '68.2M',
    flops: '257.8G',
    mapVal: '53.9',
    speed: '479ms',
    description: 'Maximum accuracy for critical applications',
    recommended: false,
    requirements: { gpu: true, minRam: '16GB' },
    inputSize: 640,
    downloadUrl: 'yolov8x.pt',
  },

  // YOLOv11 Models
  yolov11n: {
    id: 'yolov11n',
    name: 'YOLOv11 Nano',
    family: MODEL_FAMILIES.YOLO,
    version: 'v11',
    size: 'nano',
    params: '2.6M',
    flops: '6.5G',
    mapVal: '39.5',
    speed: '50ms',
    description: 'Latest YOLO with improved architecture',
    recommended: true,
    requirements: { gpu: false, minRam: '2GB' },
    inputSize: 640,
    downloadUrl: 'yolo11n.pt',
  },
  yolov11s: {
    id: 'yolov11s',
    name: 'YOLOv11 Small',
    family: MODEL_FAMILIES.YOLO,
    version: 'v11',
    size: 'small',
    params: '9.4M',
    flops: '21.5G',
    mapVal: '47.0',
    speed: '85ms',
    description: 'Small YOLOv11 with C3k2 blocks',
    recommended: true,
    requirements: { gpu: false, minRam: '4GB' },
    inputSize: 640,
    downloadUrl: 'yolo11s.pt',
  },
  yolov11m: {
    id: 'yolov11m',
    name: 'YOLOv11 Medium',
    family: MODEL_FAMILIES.YOLO,
    version: 'v11',
    size: 'medium',
    params: '20.1M',
    flops: '68.0G',
    mapVal: '51.5',
    speed: '155ms',
    description: 'Medium YOLOv11 with attention',
    recommended: false,
    requirements: { gpu: true, minRam: '8GB' },
    inputSize: 640,
    downloadUrl: 'yolo11m.pt',
  },
  yolov11l: {
    id: 'yolov11l',
    name: 'YOLOv11 Large',
    family: MODEL_FAMILIES.YOLO,
    version: 'v11',
    size: 'large',
    params: '25.3M',
    flops: '86.9G',
    mapVal: '53.4',
    speed: '200ms',
    description: 'Large YOLOv11 for production',
    recommended: false,
    requirements: { gpu: true, minRam: '12GB' },
    inputSize: 640,
    downloadUrl: 'yolo11l.pt',
  },
  yolov11x: {
    id: 'yolov11x',
    name: 'YOLOv11 XLarge',
    family: MODEL_FAMILIES.YOLO,
    version: 'v11',
    size: 'xlarge',
    params: '56.9M',
    flops: '194.9G',
    mapVal: '54.7',
    speed: '350ms',
    description: 'Maximum accuracy YOLOv11',
    recommended: false,
    requirements: { gpu: true, minRam: '16GB' },
    inputSize: 640,
    downloadUrl: 'yolo11x.pt',
  },

  // YOLOv12 Models
  yolov12n: {
    id: 'yolov12n',
    name: 'YOLOv12 Nano',
    family: MODEL_FAMILIES.YOLO,
    version: 'v12',
    size: 'nano',
    params: '2.6M',
    flops: '6.5G',
    mapVal: '40.6',
    speed: '48ms',
    description: 'Latest YOLOv12 with attention-centric design',
    recommended: true,
    requirements: { gpu: false, minRam: '2GB' },
    inputSize: 640,
    downloadUrl: 'yolo12n.pt',
  },
  yolov12s: {
    id: 'yolov12s',
    name: 'YOLOv12 Small',
    family: MODEL_FAMILIES.YOLO,
    version: 'v12',
    size: 'small',
    params: '9.3M',
    flops: '21.4G',
    mapVal: '48.0',
    speed: '82ms',
    description: 'Small YOLOv12 with area attention',
    recommended: true,
    requirements: { gpu: false, minRam: '4GB' },
    inputSize: 640,
    downloadUrl: 'yolo12s.pt',
  },
  yolov12m: {
    id: 'yolov12m',
    name: 'YOLOv12 Medium',
    family: MODEL_FAMILIES.YOLO,
    version: 'v12',
    size: 'medium',
    params: '20.2M',
    flops: '67.5G',
    mapVal: '52.5',
    speed: '150ms',
    description: 'Medium YOLOv12 for balanced performance',
    recommended: false,
    requirements: { gpu: true, minRam: '8GB' },
    inputSize: 640,
    downloadUrl: 'yolo12m.pt',
  },
  yolov12l: {
    id: 'yolov12l',
    name: 'YOLOv12 Large',
    family: MODEL_FAMILIES.YOLO,
    version: 'v12',
    size: 'large',
    params: '26.4M',
    flops: '88.9G',
    mapVal: '54.4',
    speed: '195ms',
    description: 'Large YOLOv12 for production',
    recommended: false,
    requirements: { gpu: true, minRam: '12GB' },
    inputSize: 640,
    downloadUrl: 'yolo12l.pt',
  },
  yolov12x: {
    id: 'yolov12x',
    name: 'YOLOv12 XLarge',
    family: MODEL_FAMILIES.YOLO,
    version: 'v12',
    size: 'xlarge',
    params: '59.1M',
    flops: '199.0G',
    mapVal: '55.8',
    speed: '345ms',
    description: 'Maximum accuracy YOLOv12',
    recommended: false,
    requirements: { gpu: true, minRam: '16GB' },
    inputSize: 640,
    downloadUrl: 'yolo12x.pt',
  },

  // Vajra Models
  vajrav1n: {
    id: 'vajrav1n',
    name: 'Vajra V1 Nano',
    family: MODEL_FAMILIES.VAJRA,
    version: 'v1',
    size: 'nano',
    params: '2.8M',
    flops: '7.2G',
    mapVal: '40.1',
    speed: '48ms',
    description: 'Vajra optimized for edge deployment',
    recommended: false,
    requirements: { gpu: false, minRam: '2GB' },
    inputSize: 640,
    downloadUrl: 'vajra-v1-nano.pt',
  },
  vajrav1s: {
    id: 'vajrav1s',
    name: 'Vajra V1 Small',
    family: MODEL_FAMILIES.VAJRA,
    version: 'v1',
    size: 'small',
    params: '10.5M',
    flops: '25.8G',
    mapVal: '47.8',
    speed: '95ms',
    description: 'Small Vajra with efficient backbone',
    recommended: true,
    requirements: { gpu: false, minRam: '4GB' },
    inputSize: 640,
    downloadUrl: 'vajra-v1-small.pt',
  },
  vajrav1m: {
    id: 'vajrav1m',
    name: 'Vajra V1 Medium',
    family: MODEL_FAMILIES.VAJRA,
    version: 'v1',
    size: 'medium',
    params: '22.4M',
    flops: '65.3G',
    mapVal: '52.3',
    speed: '180ms',
    description: 'Medium Vajra for balanced performance',
    recommended: false,
    requirements: { gpu: true, minRam: '8GB' },
    inputSize: 640,
    downloadUrl: 'vajra-v1-medium.pt',
  },
  vajrav1l: {
    id: 'vajrav1l',
    name: 'Vajra V1 Large',
    family: MODEL_FAMILIES.VAJRA,
    version: 'v1',
    size: 'large',
    params: '45.2M',
    flops: '142.5G',
    mapVal: '54.8',
    speed: '320ms',
    description: 'Large Vajra for high accuracy',
    recommended: false,
    requirements: { gpu: true, minRam: '12GB' },
    inputSize: 640,
    downloadUrl: 'vajra-v1-large.pt',
  },
  vajrav2s: {
    id: 'vajrav2s',
    name: 'Vajra V2 Small',
    family: MODEL_FAMILIES.VAJRA,
    version: 'v2',
    size: 'small',
    params: '11.2M',
    flops: '28.4G',
    mapVal: '49.2',
    speed: '88ms',
    description: 'Vajra V2 with improved attention',
    recommended: true,
    requirements: { gpu: false, minRam: '4GB' },
    inputSize: 640,
    downloadUrl: 'vajra-v2-small.pt',
  },
  vajrav2m: {
    id: 'vajrav2m',
    name: 'Vajra V2 Medium',
    family: MODEL_FAMILIES.VAJRA,
    version: 'v2',
    size: 'medium',
    params: '24.8M',
    flops: '72.1G',
    mapVal: '53.8',
    speed: '165ms',
    description: 'Vajra V2 with spatial attention',
    recommended: false,
    requirements: { gpu: true, minRam: '8GB' },
    inputSize: 640,
    downloadUrl: 'vajra-v2-medium.pt',
  },

};

// Group models by version for easy filtering
export const getModelsByVersion = (version) => {
  return Object.values(MODEL_CONFIGS).filter(m => m.version === version);
};

// Group models by family
export const getModelsByFamily = (family) => {
  return Object.values(MODEL_CONFIGS).filter(m => m.family === family);
};

// Get recommended models
export const getRecommendedModels = () => {
  return Object.values(MODEL_CONFIGS).filter(m => m.recommended);
};

// Get all versions
export const YOLO_VERSIONS = ['v8', 'v11', 'v12'];

// Training presets
export const TRAINING_PRESETS = {
  fast: {
    name: 'Fast Training',
    description: 'Quick training for testing',
    epochs: 25,
    batchSize: 16,
    imgSize: 416,
    patience: 5,
    optimizer: 'AdamW',
    lr: 0.01,
  },
  balanced: {
    name: 'Balanced',
    description: 'Good balance of speed and accuracy',
    epochs: 50,
    batchSize: 16,
    imgSize: 640,
    patience: 10,
    optimizer: 'AdamW',
    lr: 0.01,
  },
  accurate: {
    name: 'High Accuracy',
    description: 'Best accuracy, longer training',
    epochs: 100,
    batchSize: 8,
    imgSize: 640,
    patience: 20,
    optimizer: 'SGD',
    lr: 0.001,
  },
  production: {
    name: 'Production',
    description: 'For deployment-ready models',
    epochs: 150,
    batchSize: 8,
    imgSize: 640,
    patience: 30,
    optimizer: 'SGD',
    lr: 0.001,
  },
};

// Data augmentation presets
export const AUGMENTATION_PRESETS = {
  none: {
    name: 'None',
    description: 'No augmentation',
    hsv_h: 0,
    hsv_s: 0,
    hsv_v: 0,
    degrees: 0,
    translate: 0,
    scale: 0,
    shear: 0,
    flipud: 0,
    fliplr: 0,
    mosaic: 0,
    mixup: 0,
  },
  light: {
    name: 'Light',
    description: 'Minimal augmentation',
    hsv_h: 0.015,
    hsv_s: 0.4,
    hsv_v: 0.3,
    degrees: 0,
    translate: 0.1,
    scale: 0.3,
    shear: 0,
    flipud: 0,
    fliplr: 0.5,
    mosaic: 0.5,
    mixup: 0,
  },
  medium: {
    name: 'Medium',
    description: 'Balanced augmentation',
    hsv_h: 0.015,
    hsv_s: 0.7,
    hsv_v: 0.4,
    degrees: 10,
    translate: 0.1,
    scale: 0.5,
    shear: 5,
    flipud: 0.2,
    fliplr: 0.5,
    mosaic: 1.0,
    mixup: 0.1,
  },
  heavy: {
    name: 'Heavy',
    description: 'Maximum augmentation for small datasets',
    hsv_h: 0.02,
    hsv_s: 0.9,
    hsv_v: 0.5,
    degrees: 20,
    translate: 0.2,
    scale: 0.9,
    shear: 10,
    flipud: 0.5,
    fliplr: 0.5,
    mosaic: 1.0,
    mixup: 0.3,
  },
};

export default MODEL_CONFIGS;
